<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cms tracker'                                                                                                                                => 'Трекер страниц',
    'Cms tracker setting'                                                                                                                        => 'Настройки трекера',
    'Cookie Life Time'                                                                                                                           => 'Время жизни Cookie',
    'Default mode'                                                                                                                               => 'Обычный режим',
    'Enable Tracking'                                                                                                                            => 'Включить трекинг',
    'Enable synchronize with Google Analytics'                                                                                                   => 'Включить синхронизвцию с Google Analytics',
    'Google Analytic Api Key'                                                                                                                    => 'Google Analytics Api ключ',
    'Google Analytic Profile Id'                                                                                                                 => 'Google Analytic Profile Id',
    'Hits'                                                                                                                                       => '',
    'ID'                                                                                                                                         => '',
    'Main'                                                                                                                                       => 'Основное',
    'Model Class'                                                                                                                                => '',
    'Pk'                                                                                                                                         => '',
    'Setting'                                                                                                                                    => 'Настройки',
    'Sync At'                                                                                                                                    => '',
    'Sync Frequency (in seconds)'                                                                                                                => 'Частота синхронизации (в секундах)',
    'Synchronize with Google Analytics'                                                                                                          => 'Синхронизвция с Google Analytics',
    'This option disables and enables the operation of the entire component. Turning off all its other settings will not be taken into account.' => 'Эта опция, отключает и включает работу всего компонента. Отключив ее все другие настройки не будут учитываться.',
    'Time (in seconds) after which the user’s visit is defined as a new visit'                                                                   => 'Время (в секундах)  после истечение которого визит пользователя определяется как новое посещение ',
    'Tracking Setting'                                                                                                                           => 'Настройки трекинга',
    'Tracking mode'                                                                                                                              => 'Механизм треккинга',
    'Type'                                                                                                                                       => '',
    'Use ajax'                                                                                                                                   => 'Использовать AJAX',
    'Valid .json file'                                                                                                                           => 'Действительный .json файл',
];
